# NumPy Introduction - Basics of the fundamental package for scientific computing with Python

In [1]:
import numpy as np

#### The Main object of NumPy is a homogeneous multidimensional array. It contains a table of elements - all of the same type - and is indexed by integers. The dimensions in NumPy are called axes. The numbers of axes are called rank. The following examples shows how to create, handle and operate with NumPy arrays.

### Example 1 - NumPy Array handling

In [2]:
arr = np.arange(0, 20, 2)  # Creates an array from 0 to 20 in steps of 2
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [3]:
arr = arr.reshape(5, 2)  # Changing the dimensions of the array
arr

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [4]:
arr.ndim  # The rank of the array (numbers of dimensions)

2

In [5]:
arr.itemsize  # Size of bytes for each element

8

In [6]:
arr.size  # Numbers of elements in array

10

In [7]:
type(arr)  # Python type

numpy.ndarray

### Example 2 - NumPy Array Creation

In [8]:
list = range(0, 20)

In [9]:
arr = np.array(list)  # Converting list to numpy.ndarray
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
arr = np.array([1, 2, 3])  # Of course this works too
arr

array([1, 2, 3])

In [11]:
arr = np.array((1, 2, 3))  # Also works with tuples
arr

array([1, 2, 3])

In [12]:
arr = np.array([(1, 2, 3), [4, 5, 6], (7, 8, 9)])  # Multidimensional mix of list and tuples
arr  # Look at the syntax! Square brackets around all list and tuples

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr = np.zeros((5, 6))  # Creating a 5*6 array with zeros, also works with ones
arr  # Standard type is float64, you can change it by passing dtype=<TYPE> as a second parameter

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [14]:
arr = np.eye(4)  # Creates multidimensional array with diagonal ones
arr

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

### Example 3 - Operations with NumPy Arrays

In [15]:
arr = np.array([2, 4, 6, 8, 10])
arr

array([ 2,  4,  6,  8, 10])

In [16]:
another_arr = np.ones(5, dtype='int64')
another_arr

array([1, 1, 1, 1, 1])

In [17]:
result = arr - another_arr
result

array([1, 3, 5, 7, 9])

In [18]:
result * np.pi

array([  3.14159265,   9.42477796,  15.70796327,  21.99114858,  28.27433388])

In [19]:
MATRIX_A = np.array([[1, 3], [2, 4]])  # Creating a 2*2 matrix (basically a 2*2 dimensional array)
MATRIX_A

array([[1, 3],
       [2, 4]])

In [20]:
MATRIX_B = np.array([[1, 2], [3, 4]])  # Another one
MATRIX_B

array([[1, 2],
       [3, 4]])

In [21]:
MATRIX_A * MATRIX_B  # Attention! Product working elementwise!

array([[ 1,  6],
       [ 6, 16]])

In [22]:
np.dot(MATRIX_A, MATRIX_B)  # A way of calculating the matrix product

array([[10, 14],
       [14, 20]])

In [23]:
MATRIX_A @ MATRIX_B  # Alternative for np.dot

array([[10, 14],
       [14, 20]])

In [24]:
arr = np.ones((5, 6), dtype=int)
arr

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [25]:
arr + np.ones((5, 6))

array([[ 2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.]])

In [26]:
arr = np.random.random((4, 5))  # Creating random array elements between 0 and 1
arr

array([[ 0.76049082,  0.74709076,  0.59803985,  0.561613  ,  0.78680817],
       [ 0.00596629,  0.57811889,  0.97020026,  0.89291994,  0.86709653],
       [ 0.56167561,  0.43946085,  0.35372907,  0.9946344 ,  0.38680908],
       [ 0.91244472,  0.21769686,  0.97998551,  0.5329158 ,  0.99248787]])

In [27]:
arr.sum()  # Sum of all elements in arr

13.140184269979361

In [28]:
arr.min()  # Minimum in arr

0.0059662900822806675

In [29]:
arr.max()  # Max in arr

0.99463440139801196

In [30]:
arr.sum(axis=0)  # Sum of each column

array([ 2.24057745,  1.98236735,  2.90195469,  2.98208314,  3.03320164])

In [31]:
arr.sum(axis=1)  # Sum of each row

array([ 3.4540426 ,  3.31430191,  2.73630901,  3.63553076])

In [32]:
arr.max(axis=1)  # Maximum of each row

array([ 0.78680817,  0.97020026,  0.9946344 ,  0.99248787])

In [33]:
arr.cumsum(axis=0)  # cumulative sum along each column

array([[ 0.76049082,  0.74709076,  0.59803985,  0.561613  ,  0.78680817],
       [ 0.76645711,  1.32520965,  1.56824011,  1.45453293,  1.6539047 ],
       [ 1.32813272,  1.7646705 ,  1.92196918,  2.44916734,  2.04071378],
       [ 2.24057745,  1.98236735,  2.90195469,  2.98208314,  3.03320164]])

In [34]:
arr.cumprod(axis=1)  # cumulative product along each row

array([[ 0.76049082,  0.56815567,  0.33977973,  0.19082471,  0.15014244],
       [ 0.00596629,  0.00344922,  0.00334644,  0.0029881 ,  0.00259097],
       [ 0.56167561,  0.24683444,  0.08731252,  0.08684403,  0.03359206],
       [ 0.91244472,  0.19863635,  0.19466074,  0.10373779,  0.10295849]])

### Example 4 - Universal Functions (mathematical functions like sin, cos, exp)

In [35]:
arr = np.arange(5)
np.exp(arr)  # exponential function

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,  54.59815003])

In [36]:
np.sqrt(arr)  # square root function

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ])

In [37]:
np.add(np.exp(arr), np.sqrt(arr))  # Addition

array([  1.        ,   3.71828183,   8.80326966,  21.81758773,  56.59815003])

In [38]:
arr = np.exp(np.arange(20))
np.mean(arr)  # Calculating the mean (average)

14117742.106511313

In [39]:
np.median(arr)  # The median value

15064.77486119105

### Example 5 - Indexing, Slicing and Iterating through one dimensional arrays (standard Python)

In [40]:
arr = np.arange(20)  # Array has now indexes from 0 to 19
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
arr[2]  # third element, values represents indexes in arr

2

In [42]:
arr = arr**2
arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [43]:
arr[3:6]  # Slicing between indexes

array([ 9, 16, 25])

In [44]:
arr[:10]  # Slicing to an index

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [45]:
arr[10:]  # Slicing from an index

array([100, 121, 144, 169, 196, 225, 256, 289, 324, 361])

In [46]:
for val in arr:  # Iterating through an array
    print(val*0.25)

0.0
0.25
1.0
2.25
4.0
6.25
9.0
12.25
16.0
20.25
25.0
30.25
36.0
42.25
49.0
56.25
64.0
72.25
81.0
90.25


### Example 6 - Dealing wih multidimensional arrays

In [47]:
arr = np.arange(0, 20).reshape(4, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [48]:
arr[2, 4]  # access to element in array

14

In [49]:
arr[1:3, 1]  # Same slicing syntax like with one dimensional arrays

array([ 6, 11])

In [50]:
arr[:, 1]  # slicing whole column

array([ 1,  6, 11, 16])

In [51]:
arr[1, :]  # slicing whole row

array([5, 6, 7, 8, 9])

In [52]:
arr[1]  # Accessing second row (equivalent to above)

array([5, 6, 7, 8, 9])

In [53]:
arr[-1]  # Last row

array([15, 16, 17, 18, 19])

In [54]:
arr.shape

(4, 5)

In [55]:
for row in arr:  # Iterating over the rows in arr
    print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [56]:
for row in arr:  # Iterating over the rows in arr
    for val in row:  # Iterating over each value in each row
        print(val)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [57]:
for val in arr.flat:  # Equivalent to above, but using the flat attribute (iterator over all elements)
    print(val)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
