# NumPy Introduction - Basics of the fundamental package for scientific computing with Python

In [1]:
import numpy as np

#### The Main object of NumPy is a homogeneous multidimensional array. It contains a table of elements - all of the same type - and is indexed by integers. The dimensions in NumPy are called axes. The numbers of axes are called rank. The following examples shows how to create, handle and operate with NumPy arrays.

### Example 1 - NumPy Array handling

In [2]:
arr = np.arange(0, 20, 2)  # Creates an array from 0 to 20 in steps of 2
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [3]:
arr = arr.reshape(5, 2)  # Changing the dimensions of the array
arr

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [4]:
arr.ndim  # The rank of the array (numbers of dimensions)

2

In [5]:
arr.itemsize  # Size of bytes for each element

8

In [6]:
arr.size  # Numbers of elements in array

10

In [7]:
type(arr)  # Python type

numpy.ndarray

### Example 2 - NumPy Array Creation

In [8]:
list = range(0, 20)

In [9]:
arr = np.array(list)  # Converting list to numpy.ndarray
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
arr = np.array([1, 2, 3])  # Of course this works too
arr

array([1, 2, 3])

In [11]:
arr = np.array((1, 2, 3))  # Also works with tuples
arr

In [12]:
arr = np.array([(1, 2, 3), [4, 5, 6], (7, 8, 9)])  # Multidimensional mix of list and tuples
arr  # Look at the syntax! Square brackets around all list and tuples

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr = np.zeros((5, 6))  # Creating a 5*6 array with zeros, also works with ones
arr  # Standard type is float64, you can change it by passing dtype=<TYPE> as a second parameter

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [13]:
arr = np.eye(4)  # Creates multidimensional array with diagonal ones
arr

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

### Example 3 - Operations with NumPy Arrays

In [15]:
arr = np.array([2, 4, 6, 8, 10])
arr

array([ 2,  4,  6,  8, 10])

In [16]:
another_arr = np.ones(5, dtype='int64')
another_arr

array([1, 1, 1, 1, 1])

In [17]:
result = arr - another_arr
result

array([1, 3, 5, 7, 9])

In [18]:
result * np.pi

array([  3.14159265,   9.42477796,  15.70796327,  21.99114858,  28.27433388])

In [19]:
MATRIX_A = np.array([[1, 3], [2, 4]])  # Creating a 2*2 matrix (basically a 2*2 dimensional array)
MATRIX_A

array([[1, 3],
       [2, 4]])

In [20]:
MATRIX_B = np.array([[1, 2], [3, 4]])  # Another one
MATRIX_B

array([[1, 2],
       [3, 4]])

In [21]:
MATRIX_A * MATRIX_B  # Attention! Product working elementwise!

array([[ 1,  6],
       [ 6, 16]])

In [22]:
np.dot(MATRIX_A, MATRIX_B)  # A way of calculating the matrix product

array([[10, 14],
       [14, 20]])

In [23]:
MATRIX_A @ MATRIX_B  # Alternative for np.dot

array([[10, 14],
       [14, 20]])

In [24]:
arr = np.ones((5, 6), dtype=int)
arr

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [25]:
arr + np.ones((5, 6))

array([[ 2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.]])

In [26]:
arr = np.random.random((4, 5))  # Creating random array elements between 0 and 1
arr

In [27]:
arr.sum()  # Sum of all elements in arr

11.677850261474287

In [28]:
arr.min()  # Minimum in arr

0.075878078819878181

In [29]:
arr.max()  # Max in arr

0.99388235496362587

In [30]:
arr.sum(axis=0)  # Sum of each column

array([ 2.82472238,  2.80298805,  1.74797208,  1.77653605,  2.5256317 ])

In [31]:
arr.sum(axis=1)  # Sum of each row

array([ 3.41347424,  2.27426622,  2.6806253 ,  3.3094845 ])

In [32]:
arr.max(axis=1)  # Maximum of each row

array([ 0.87426066,  0.63590196,  0.77606434,  0.99388235])

In [33]:
arr.cumsum(axis=0)  # cumulative sum along each column

array([[ 0.84199948,  0.57350735,  0.4769277 ,  0.87426066,  0.64677905],
       [ 1.30365981,  1.20940931,  0.73261426,  1.34202425,  1.10003283],
       [ 1.83084002,  1.81732938,  1.14344123,  1.70065797,  1.87609717],
       [ 2.82472238,  2.80298805,  1.74797208,  1.77653605,  2.5256317 ]])

In [34]:
arr.cumprod(axis=1)  # cumulative product along each row

array([[ 0.84199948,  0.48289289,  0.23030499,  0.2013466 ,  0.13022676],
       [ 0.46166033,  0.29357071,  0.07506209,  0.03511131,  0.01591433],
       [ 0.52718021,  0.32048343,  0.13166323,  0.04721888,  0.03664489],
       [ 0.99388235,  0.97962877,  0.59221582,  0.0449362 ,  0.02918761]])

### Example 4 - Universal Functions (mathematical functions like sin, cos, exp)

In [36]:
arr = np.arange(5)
np.exp(arr)  # exponential function

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,  54.59815003])

In [37]:
np.sqrt(arr)  # square root function

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ])

In [38]:
np.add(np.exp(arr), np.sqrt(arr))  # Addition

array([  1.        ,   3.71828183,   8.80326966,  21.81758773,  56.59815003])

In [45]:
arr = np.exp(np.arange(20))
np.mean(arr)  # Calculating the mean (average)

14117742.106511313

In [46]:
np.median(arr)  # The median value

15064.77486119105

### Example 5 - Indexing, Slicing and Iterating through one dimensional arrays (standard Python)

In [50]:
arr = np.arange(20)  # Array has now indexes from 0 to 19
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [51]:
arr[2]  # third element, values represents indexes in arr

2

In [53]:
arr = arr**2
arr

array([     0,      1,     16,     81,    256,    625,   1296,   2401,
         4096,   6561,  10000,  14641,  20736,  28561,  38416,  50625,
        65536,  83521, 104976, 130321])

In [56]:
arr[3:6]  # Slicing between indexes

array([ 81, 256, 625])

In [57]:
arr[:10]  # Slicing to an index

array([   0,    1,   16,   81,  256,  625, 1296, 2401, 4096, 6561])

In [58]:
arr[10:]  # Slicing from an index

array([ 10000,  14641,  20736,  28561,  38416,  50625,  65536,  83521,
       104976, 130321])

In [60]:
for val in arr:  # Iterating through an array
    print(val*0.25)

0.0
0.25
4.0
20.25
64.0
156.25
324.0
600.25
1024.0
1640.25
2500.0
3660.25
5184.0
7140.25
9604.0
12656.25
16384.0
20880.25
26244.0
32580.25


### Example 6 - Dealing wih multidimensional arrays