In [2]:
import numpy as np

In [12]:
arr = np.arange(0, 20, 2)  # Creates an array from 0 to 20 in steps of 2
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
arr = arr.reshape(5, 2)  # Changing the dimensions of the array
arr

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [16]:
arr.ndim  # The rank of the array (numbers of dimensions)

2

In [20]:
arr.itemsize  # Size of bytes for each element

8

In [21]:
arr.size  # Numbers of elements in array

10

In [34]:
type(arr)  # Python type

numpy.ndarray

In [30]:
list = range(0, 20)

In [31]:
arr = np.array(list)  # Converting list to numpy.ndarray
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
arr = np.array([1, 2, 3])  # Of course this works too
arr

array([1, 2, 3])

In [35]:
arr = np.array((1, 2, 3))  # Also works with tuples
arr

array([1, 2, 3])

In [53]:
arr = np.array([(1, 2, 3), [4, 5, 6], (7, 8, 9)])  # Multidimensional mix of list and tuples
arr  # Look at the syntax! Square brackets around all list and tuples

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
arr = np.zeros((5, 6))  # Creating a 5*6 array with zeros, also works with ones
arr  # Standard type is float64, you can change it by passing dtype=<TYPE> as a second parameter

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [55]:
arr = np.eye(4)  # Creates multidimensional array with diagonal ones
arr

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [3]:
arr = np.array([2, 4, 6, 8, 10])
arr

array([ 2,  4,  6,  8, 10])

In [9]:
another_arr = np.ones(5, dtype='int64')
another_arr

array([1, 1, 1, 1, 1])

In [10]:
result = arr - another_arr
result

array([1, 3, 5, 7, 9])

In [13]:
result * np.pi

array([  3.14159265,   9.42477796,  15.70796327,  21.99114858,  28.27433388])

In [24]:
MATRIX_A = np.array([[1, 3], [2, 4]])  # Creating a 2*2 matrix (basically a 2*2 dimensional array)
MATRIX_A

array([[1, 3],
       [2, 4]])

In [25]:
MATRIX_B = np.array([[1, 2], [3, 4]])  # Another one
MATRIX_B

array([[1, 2],
       [3, 4]])

In [30]:
MATRIX_A * MATRIX_B  # Attention! Product working elementwise!

array([[ 1,  6],
       [ 6, 16]])

In [33]:
np.dot(MATRIX_A, MATRIX_B)  # A way of calculating the matrix product

array([[10, 14],
       [14, 20]])

In [34]:
MATRIX_A @ MATRIX_B  # Alternative for np.dot

array([[10, 14],
       [14, 20]])

In [36]:
arr = np.ones((5, 6), dtype=int)
arr

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [37]:
arr + np.ones((5, 6))

array([[ 2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.]])

In [40]:
arr = np.random.random((4, 5))  # Creating random array elements between 0 and 1
arr

array([[ 0.02809537,  0.93589716,  0.9710442 ,  0.37347205,  0.0196119 ],
       [ 0.2202484 ,  0.80769175,  0.12947889,  0.73497302,  0.89146284],
       [ 0.02432126,  0.68167661,  0.62791176,  0.99782662,  0.28564971],
       [ 0.82234574,  0.82669904,  0.66023452,  0.67888313,  0.61667433]])

In [41]:
arr.sum()  # Sum of all elements in arr

11.334198284964984

In [42]:
arr.min()  # Minimum in arr

0.019611898761617952

In [43]:
arr.max()  # Max in arr

0.99782661735535794

In [45]:
arr.sum(axis=0)  # Sum of each column

array([ 1.09501077,  3.25196455,  2.38866937,  2.78515481,  1.81339878])

In [46]:
arr.sum(axis=1)  # Sum of each row

array([ 2.32812067,  2.7838549 ,  2.61738596,  3.60483675])

In [49]:
arr.max(axis=1)  # Maximum of each row

array([ 0.9710442 ,  0.89146284,  0.99782662,  0.82669904])

In [50]:
arr.cumsum(axis=0)  # cumulative sum along each column

array([[ 0.02809537,  0.93589716,  0.9710442 ,  0.37347205,  0.0196119 ],
       [ 0.24834377,  1.74358891,  1.10052309,  1.10844507,  0.91107474],
       [ 0.27266504,  2.42526551,  1.72843484,  2.10627169,  1.19672445],
       [ 1.09501077,  3.25196455,  2.38866937,  2.78515481,  1.81339878]])

In [51]:
arr.cumprod(axis=1)  # cumulative product along each row

array([[  2.80953670e-02,   2.62943741e-02,   2.55329994e-02,
          9.53586157e-03,   1.87016352e-04],
       [  2.20248405e-01,   1.77892819e-01,   2.30333650e-02,
          1.69289019e-02,   1.50914869e-02],
       [  2.43212648e-02,   1.65792373e-02,   1.04102980e-02,
          1.03876724e-02,   2.96723564e-03],
       [  8.22345738e-01,   6.79832434e-01,   4.48848842e-01,
          3.04715905e-01,   1.87910475e-01]])